users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views
app_name='[users]'
#登录页面
urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'),name='login'),
    url(r'logout',views.logout_view,name='logout'),
    url(r'^register/$', views.register, name='register'),
]

web_test/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include(('webapp.urls'),namespace='webapp')),
    path(r'users/',include(('users.urls'),namespace='users'))
]

webapp/urls.py
#url of webapp
from django.conf.urls import url, re_path
from . import views


app_name='[webapp]'

urlpatterns=[
    #主页
    url(r'^$',views.index,name='index'),
    #显示所有主题
    re_path(r'^topics/$', views.topics, name='topics'),
    re_path(r'topics/(?P<topic_id>\d+)/$', views.topic,name='topic'),
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry')
]

users/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='entries'

    def __str__(self):
        return self.text[:50]+'...'

webapp/forms.py
from django import forms
from .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text':''}
        widgets={"text":forms.Textarea(attrs={'cols':80})}

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('webapp:index'))

def register(request):
    #注册新用户
    if request.method!='POST':
        #显示空表单
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user=form.save()
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('webapp:index'))
    context={'form':form}
    return render(request, 'users/register.html',context)

webapp/views.py
from django.shortcuts import render
from .models import Topic, Entry
from django.http import HttpResponseRedirect, Http404
from  django.urls import reverse
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
# Create your views here.
#显示主页
def index(request):
    return render(request,'webapp/index.html')

#显示主题
@login_required
def topics(request):
    topics=Topic.objects.filter(owner=request.user).order_by('date_added')
    context={'topics':topics}
    return render(request,'webapp/topics.html',context)

#显示单个主题及其所有条目
@login_required
def topic(request, topic_id):
    topic=Topic.objects.get(id=topic_id)
    if topic.owner!=request.user:
        raise Http404

    entries=topic.entry_set.order_by('-date_added')
    context={'topic':topic,'entries':entries}
    return render(request, 'webapp/topic.html',context)


#添加新主题
@login_required
def new_topic(request):
    if request.method!='POST':
        #未提交数据：创建一个新表单
        form=TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form=TopicForm(request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('webapp:topics'))
    context={'form':form}
    return render(request,'webapp/new_topic.html',context)

@login_required
def edit_entry(request, entry_id):
    #编辑目录
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner!=request.user:
        raise Http404
    if request.method!='POST':
        form=EntryForm(instance=entry)
    else:
        form=EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webapp:topic', args=[topic.id]))
    context={'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'webapp/edit_entry.html',context)


@login_required
def new_entry(request, topic_id):
    #在特定主题中添加目录
    topic=Topic.objects.get(id=topic_id)

    if request.method!='POST':
        #未提交数据，创建一个空表单
        form=EntryForm()
    else:
        #POST提交的数据，对数据进行处理
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('webapp:topic',args=[topic_id]))
    context={'topic':topic, 'form':form}
    return render(request,'webapp/new_entry.html',context)

users/templates/users/login.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}

{% block header %}
<div style="padding:15px">
    <h2>Log in to your account.</h2>
</div>
{% endblock header %}


{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<div class="'container">
    <div style="padding:15px; width:50%">
        <form method="post" action="{% url 'users:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit">log in</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'webapp:index' %}" />
        </form>
    </div>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends "webapp/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<form method="post" action="{% url 'users:register' %}">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">register</button>
<input type="hidden" name="next" value="{% url 'webapp:index' %}" />
</form>

</body>
</html>

{% endblock content %}

webapp/templates/webapp/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Webapp</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <style>
            li{
                list-style-type: none
            }
        </style>

    </head>

<body>
<!-- Static navbar -->
<meta name="viewpoint" content="width=device-width"/>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'webapp:index' %}">Learning Log</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'webapp:topics' %}">Topics</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
                {% else %}
                <li><h4><a href="{% url 'users:login' %}">sign in</a> or <a href="{% url 'users:register' %}">sign up</a></h4></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div calss="container">
    <div class="page header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>
</body>
</html>

webapp/templates/webapp/edit_entry.html
{% extends "webapp/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit entry</title>
</head>
<body>
<p><a href="{% url 'webapp:topic' topic.id %}">{{topic}}</a> </p>
<p>Edit entry</p>
<form action="{% url 'webapp:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">save changes</button>
</form>
</body>
</html>
{% endblock content %}

webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1 align="center">Learning log</h1>
    </div>
{% endblock header %}

{% block content %}

<h2>
    {% if user.is_authenticated %}
    <li>
        This website is under commissioning. Let's start <a href="{% url 'webapp:topics' %}">making your own learning log</a></h2>
    </li>
    {% else %}
    <li>
        This website is under commissioning. <a href="{% url 'users:login' %}">sign in</a> or <a href="{% url 'users:register' %}">sign up</a> to make your own learning log.
    </li>
    {% endif %}
</h2>

{% endblock content %}

webapp/templates/webapp/new_entry.html
{% extends "webapp/base.html" %}
{% block content %}
<p><a href="{% url 'webapp:topic' topic.id %}">{{topic}}</a> </p>
<p>Add a new entry:</p>

<form action="{% url 'webapp:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button name="submit">add entry</button>
</form>

{% endblock content %}

webapp/templates/webapp/new_topic.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Add a new topic</h2>
{% endblock header %}

{% block content %}
<div class="container">
    <div style="padding:1px; width:100%; height: 300%;">
        <form method="post" action="{% url 'webapp:new_topic' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock content %}

webapp/templates/webapp/topic.html
{% extends "webapp/base.html" %}

{% block header %}
<h2>{{topic}}</h2>
{% endblock header %}

{% block content %}

<p>
    <a href="{% url 'webapp:new_entry' topic.id %}">add new entry</a>
</p>

{% for entry in entries %}
<li>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{entry.date_added|date:'M d, Y H:i'}}
                <small>
                    <a href="{% url 'webapp:edit_entry' entry.id %}">edit entry</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
            <h4>{{entry.text|linebreaks}}</h4>
        </div>
    </div>
</li>
{% empty %}
    There are no entries for this topic yet
{% endfor %}

{% endblock content %}

webapp/templates/webapp/topics.html
{% extends "webapp/base.html" %}
{% block content %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'webapp:topic' topic.id %}">{{topic}}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>>
    {% endfor %}
</ul>
<a href="{% url 'webapp:new_topic' %}">Add a new topic</a>
</body>
</html>

{% endblock content %}